services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_database
  wait:
    image: willwill/wait-for-it
    command: -t 60 db:5432
    depends_on:
      - db
  migrations:
    image: redgate/flyway
    volumes:
      - ./sql:/flyway/sql
      - ./conf:/flyway/conf
    depends_on:
      - wait
    command: migrate -configFiles=conf/local.conf

