services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_database
  wait:
    image: willwill/wait-for-it
    command: -t 60 db:5432
    depends_on:
      - db
  migrations:
    image: redgate/flyway
    volumes:
      - ./sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/example_database
      - FLYWAY_USER=example_user
      - FLYWAY_PASSWORD=example_password
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: migrate
    depends_on:
      - wait

